//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which architecture to install. For most people, 32-bit will be fine.
        ///However, if you plan to deal with a large amount of data, you might want to consider 64-bit..
        /// </summary>
        public static string ArchDescription {
            get {
                return ResourceManager.GetString("ArchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string ArchHeader {
            get {
                return ResourceManager.GetString("ArchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackBtnText {
            get {
                return ResourceManager.GetString("BackBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-annual.
        /// </summary>
        public static string BroadBtn {
            get {
                return ResourceManager.GetString("BroadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get feature updates every six months in January and July..
        /// </summary>
        public static string BroadDescription {
            get {
                return ResourceManager.GetString("BroadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtnText {
            get {
                return ResourceManager.GetString("CancelBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which Office application do you want?.
        /// </summary>
        public static string ConfigOfficeDescription {
            get {
                return ResourceManager.GetString("ConfigOfficeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Office.
        /// </summary>
        public static string ConfigOfficeHeader {
            get {
                return ResourceManager.GetString("ConfigOfficeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomInstallBtn {
            get {
                return ResourceManager.GetString("CustomInstallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose components and languages to install or use an offline installation source..
        /// </summary>
        public static string CustomInstallDescription {
            get {
                return ResourceManager.GetString("CustomInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose my own.
        /// </summary>
        public static string CustomLangBtn {
            get {
                return ResourceManager.GetString("CustomLangBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the languages to install below..
        /// </summary>
        public static string CustomLangDescription {
            get {
                return ResourceManager.GetString("CustomLangDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Edition:.
        /// </summary>
        public static string EditionSelectDescription {
            get {
                return ResourceManager.GetString("EditionSelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportBtn {
            get {
                return ResourceManager.GetString("ExportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also export a copy of configuration file for later use..
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home or Personal.
        /// </summary>
        public static string HomeEdition {
            get {
                return ResourceManager.GetString("HomeEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install option.
        /// </summary>
        public static string InstallOptionHeader {
            get {
                return ResourceManager.GetString("InstallOptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation source.
        /// </summary>
        public static string InstallSourceHeader {
            get {
                return ResourceManager.GetString("InstallSourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the languages you want to install UI Language Pack, Proofing Tools and Help Files for..
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just download.
        /// </summary>
        public static string LayoutBtn {
            get {
                return ResourceManager.GetString("LayoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download installation files for later use..
        /// </summary>
        public static string LayoutDescription {
            get {
                return ResourceManager.GetString("LayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my system language.
        /// </summary>
        public static string MatchOSBtn {
            get {
                return ResourceManager.GetString("MatchOSBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the language of your system..
        /// </summary>
        public static string MatchOSDescription {
            get {
                return ResourceManager.GetString("MatchOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MonthlyBtn {
            get {
                return ResourceManager.GetString("MonthlyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get feature updates every one or two months..
        /// </summary>
        public static string MonthlyDecription {
            get {
                return ResourceManager.GetString("MonthlyDecription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextBtnText {
            get {
                return ResourceManager.GetString("NextBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use offline source.
        /// </summary>
        public static string OfflineBtn {
            get {
                return ResourceManager.GetString("OfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your own offline installation files..
        /// </summary>
        public static string OfflineDescription {
            get {
                return ResourceManager.GetString("OfflineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download online.
        /// </summary>
        public static string OnlineBtn {
            get {
                return ResourceManager.GetString("OnlineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the latest version from Microsoft..
        /// </summary>
        public static string OnlineDescription {
            get {
                return ResourceManager.GetString("OnlineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select product.
        /// </summary>
        public static string ProductPageHeader {
            get {
                return ResourceManager.GetString("ProductPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Project.
        /// </summary>
        public static string ProjectCheckText {
            get {
                return ResourceManager.GetString("ProjectCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of your team&apos;s plan and progress..
        /// </summary>
        public static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Plus.
        /// </summary>
        public static string ProPlusEdition {
            get {
                return ResourceManager.GetString("ProPlusEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick install.
        /// </summary>
        public static string QuickInstallBtn {
            get {
                return ResourceManager.GetString("QuickInstallBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install all components with recommended settings..
        /// </summary>
        public static string QuickInstallDescription {
            get {
                return ResourceManager.GetString("QuickInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office is now ready to be installed. Click Next to continue..
        /// </summary>
        public static string ReadyDescription_Install {
            get {
                return ResourceManager.GetString("ReadyDescription_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office is now ready to be downloaded. Click Next to continue..
        /// </summary>
        public static string ReadyDescription_Layout {
            get {
                return ResourceManager.GetString("ReadyDescription_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to roll.
        /// </summary>
        public static string ReadyHeader {
            get {
                return ResourceManager.GetString("ReadyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect for home and personal users. Office 365 Home or Personal required..
        /// </summary>
        public static string SKUDescriptionHome {
            get {
                return ResourceManager.GetString("SKUDescriptionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For enterprise users who demand professional functionalities..
        /// </summary>
        public static string SKUDescriptionProPlus {
            get {
                return ResourceManager.GetString("SKUDescriptionProPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office Suite.
        /// </summary>
        public static string SuiteCheckText {
            get {
                return ResourceManager.GetString("SuiteCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the Office apps you know and love..
        /// </summary>
        public static string SuiteDescription {
            get {
                return ResourceManager.GetString("SuiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-annual (Fast).
        /// </summary>
        public static string TargetedBtn {
            get {
                return ResourceManager.GetString("TargetedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get feature updates every six months in September and March..
        /// </summary>
        public static string TargetedDescription {
            get {
                return ResourceManager.GetString("TargetedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how often you want to receive feature updates. 
        ///Security and quality updates will be released every month..
        /// </summary>
        public static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update cycle.
        /// </summary>
        public static string UpdateHeader {
            get {
                return ResourceManager.GetString("UpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio.
        /// </summary>
        public static string VisioCheckText {
            get {
                return ResourceManager.GetString("VisioCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply create diagrams to illustrate your ideas..
        /// </summary>
        public static string VisioDescription {
            get {
                return ResourceManager.GetString("VisioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Deployment Tool.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64 Bit.
        /// </summary>
        public static string x64BtnText {
            get {
                return ResourceManager.GetString("x64BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer does not support 64-bit version of Office..
        /// </summary>
        public static string x64NotSupportText {
            get {
                return ResourceManager.GetString("x64NotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 Bit.
        /// </summary>
        public static string x86BtnText {
            get {
                return ResourceManager.GetString("x86BtnText", resourceCulture);
            }
        }
    }
}
